-- Datos iniciales para el sistema de compras y ventas
-- Ejecutar despues de supabase/schema.sql

insert into factories (name) values
  ('Alpargatas Argentinas'),
  ('Reginales FDL'),
  ('Enrique Bicicletas'),
  ('Fiorentino'),
  ('Marroquinería'),
  ('Anchus Mayorista')
on conflict (name) do nothing;

insert into clients (name, phone, note) values
  ('Agustina Masnú (Jauja)', '', ''),
  ('Andrea Menoyo', '', ''),
  ('Andrés Cafaro', '', ''),
  ('Arturo Jora', '', ''),
  ('Belén (Calcuta)', '', ''),
  ('Belén Caliri (fraternidad)', '', ''),
  ('Carla Mellado (Sanfran)', '', ''),
  ('Carolina Pedrozo (Calasanz)', '', ''),
  ('Caty mamá (mamá Mariela Cuñeti)', '', ''),
  ('Celeste Atiye (Calasanz)', '', ''),
  ('Euge Pozzoli', '', ''),
  ('Eva Dominguez', '', ''),
  ('Gisella Dutto', '', ''),
  ('Jorgelina (Calasanz)', '', ''),
  ('Laura vecina Mónica (Calasanz)', '', ''),
  ('Leandro Ávila', '', ''),
  ('Lili Lemos', '', ''),
  ('Manuel Moya', '', ''),
  ('María E Berrios (Sanfran)', '', ''),
  ('Mariana Aceto', '', ''),
  ('Mariel (mamá Leandro)', '', ''),
  ('Mariela amiga Laura (Calasanz)', '', ''),
  ('Marina Montesino', '', ''),
  ('Marisol Pascual (Calcuta)', '', ''),
  ('Meli Giordano (vecina)', '', ''),
  ('Merce Guiroy (Calasanz)', '', ''),
  ('Mercedes Sancho', '', ''),
  ('Micaela Duin (vecina)', '', ''),
  ('Mónica Lledó', '', ''),
  ('Naty (amiga Mariana Aceto)', '', ''),
  ('Nerina Martínez', '', ''),
  ('Pablo Pabezka', '', ''),
  ('Padre Eduardo', '', ''),
  ('Pía Bendolini', '', ''),
  ('Pilar Loring', '', ''),
  ('Silvia Sol', '', ''),
  ('Susi Morales', '', ''),
  ('Violeta (fraternidad)', '', ''),
  ('Yani vecina', '', ''),
  ('Yisela Aguilera (Calasanz)', '', '');

insert into products (name, factory_id, cost, price, stock, status)
select product_data.name, factories.id, product_data.cost, product_data.price, product_data.stock, product_data.status
from (values
  ('Alpargata yute original', 'Reginales FDL', 10800, 15120, 0, 'Activo'),
  ('Botas media caña brasileña', 'Reginales FDL', 29000, 40600, 0, 'Activo'),
  ('Chaleco gamuza', 'Reginales FDL', 18000, 25200, 0, 'Activo'),
  ('Bombachas de campo', 'Reginales FDL', 14800, 20720, 0, 'Activo'),
  ('Alpargatas simil yute', 'Reginales FDL', 4820, 6748, 0, 'Activo'),
  ('Termo bala', 'Reginales FDL', 11200, 15680, 0, 'Activo'),
  ('Set juego regional', 'Reginales FDL', 5990, 8386, 0, 'Activo'),
  ('Bombacha de campo grafa', 'Reginales FDL', 14000, 19600, 0, 'Activo'),
  ('Cinturón trenzado combinado x 12', 'Reginales FDL', 5000, 7000, 0, 'Activo'),
  ('Boina hilo', 'Reginales FDL', 5000, 7000, 0, 'Activo'),
  ('Bermuda cargo', 'Reginales FDL', 13000, 18200, 0, 'Activo'),
  ('Chomba pampa', 'Reginales FDL', 12000, 16800, 0, 'Activo'),
  ('Tabla pizzer', 'Reginales FDL', 3900, 5460, 0, 'Activo'),
  ('Bombilla alpaca plana', 'Reginales FDL', 3000, 4200, 0, 'Activo'),
  ('Ruana pampa', 'Reginales FDL', 24000, 33600, 0, 'Activo'),
  ('Billetera c volante cuero', 'Reginales FDL', 3500, 4900, 0, 'Activo'),
  ('Bufandones pahmina', 'Reginales FDL', 13000, 18200, 0, 'Activo'),
  ('Alpargata goma eva', 'Reginales FDL', 3848, 5387.2, 0, 'Activo'),
  ('Chomba pampero', 'Reginales FDL', 20860, 29204, 0, 'Activo'),
  ('Zapatillas jaguar', 'Reginales FDL', 7469, 10456.6, 0, 'Activo'),
  ('Bicicleta Explorer', 'Enrique Bicicletas', 285000, 400000, 0, 'Activo'),
  ('Zapato hombre', 'Reginales FDL', 10900, 15260, 0, 'Activo'),
  ('Cinturón bordado', 'Reginales FDL', 15000, 21000, 0, 'Activo'),
  ('Alpargatas estampadas', 'Reginales FDL', 5350, 7490, 0, 'Activo'),
  ('Camisa cuello mao', 'Reginales FDL', 15000, null, 0, 'Activo'),
  ('Campera pampa', 'Reginales FDL', 16500, null, 0, 'Activo'),
  ('Slip', 'Reginales FDL', 14500, null, 0, 'Activo'),
  ('Poncho niño', 'Reginales FDL', 15000, null, 0, 'Activo'),
  ('Poncho', 'Reginales FDL', 20000, null, 0, 'Activo'),
  ('Alpargata niño', 'Reginales FDL', 5200, null, 0, 'Activo'),
  ('Bombacha niño', 'Reginales FDL', 13000, null, 0, 'Activo'),
  ('Pañuelo cuello', 'Reginales FDL', 3700, 5900, 0, 'Activo'),
  ('Camisa clásica', 'Reginales FDL', 12000, 21000, 0, 'Activo'),
  ('Pasapañuelos', 'Reginales FDL', 1800, 2900, 0, 'Activo'),
  ('Pantalón cargo', 'Reginales FDL', 16000, null, 0, 'Activo'),
  ('Bombacha bordada', 'Reginales FDL', 16500, null, 0, 'Activo'),
  ('Mate imperial alpaca', 'Reginales FDL', 19000, null, 0, 'Activo'),
  ('Chaleco niño', 'Reginales FDL', 11000, null, 0, 'Activo'),
  ('Sombrero paja', 'Reginales FDL', 15000, null, 0, 'Activo'),
  ('Medias', 'Reginales FDL', 3000, null, 0, 'Activo'),
  ('Ruana', 'Reginales FDL', 20000, null, 0, 'Activo'),
  ('Cinturón cuero', 'Reginales FDL', 12000, 24000, 0, 'Activo'),
  ('Campera niño', 'Reginales FDL', 14500, null, 0, 'Activo'),
  ('Billetera en caja', 'Reginales FDL', 6000, null, 0, 'Activo'),
  ('Boina niño', 'Reginales FDL', 13000, null, 0, 'Activo'),
  ('Canasta matera', 'Reginales FDL', 28000, null, 0, 'Activo'),
  ('Bufandón', 'Reginales FDL', 20000, null, 0, 'Activo'),
  ('Alpargatas combinadas goma eva', 'Reginales FDL', 4560, 9800, 0, 'Activo'),
  ('Alpargatas faja pampa', 'Reginales FDL', 6900, 13800, 0, 'Activo'),
  ('Alpargatas guarda pampa goma eva', 'Reginales FDL', 4700, 9800, 0, 'Activo'),
  ('Buzo micropolar', 'Reginales FDL', 15900, null, 0, 'Activo'),
  ('Cintos hebillones', 'Reginales FDL', 9500, 16900, 0, 'Activo'),
  ('Pulsera cuero', 'Reginales FDL', 3200, 6400, 0, 'Activo'),
  ('Bicicleta turquesa', 'Enrique Bicicletas', 160200, 210000, 0, 'Activo'),
  ('Chomba pampa niño', 'Reginales FDL', 10000, null, 0, 'Activo'),
  ('Boina hilo bordada', 'Reginales FDL', 7500, 12500, 0, 'Activo'),
  ('Corbatín bordado', 'Reginales FDL', 3000, null, 0, 'Activo')
) as product_data(name, factory_name, cost, price, stock, status)
left join factories on factories.name = product_data.factory_name;
