-- Datos iniciales para el sistema de compras y ventas
-- Ejecutar despues de supabase/schema.sql

insert into factories (name) values
  ('Alpargatas Argentinas'),
  ('Regionales FDL'),
  ('Enrique Bicicletas'),
  ('Fiorentino'),
  ('Marroquinería'),
  ('Anchus Mayorista')
on conflict (name) do nothing;

insert into clients (name, phone, note) values
  ('Agustina Masnú (Jauja)', '', ''),
  ('Andrea Menoyo', '', ''),
  ('Andrés Cafaro', '', ''),
  ('Arturo Jora', '', ''),
  ('Belén (Calcuta)', '', ''),
  ('Belén Caliri (fraternidad)', '', ''),
  ('Carla Mellado (Sanfran)', '', ''),
  ('Carolina Pedrozo (Calasanz)', '', ''),
  ('Caty mamá (mamá Mariela Cuñeti)', '', ''),
  ('Celeste Atiye (Calasanz)', '', ''),
  ('Euge Pozzoli', '', ''),
  ('Eva Dominguez', '', ''),
  ('Gisella Dutto', '', ''),
  ('Jorgelina (Calasanz)', '', ''),
  ('Laura vecina Mónica (Calasanz)', '', ''),
  ('Leandro Ávila', '', ''),
  ('Lili Lemos', '', ''),
  ('Manuel Moya', '', ''),
  ('María E Berrios (Sanfran)', '', ''),
  ('Mariana Aceto', '', ''),
  ('Mariel (mamá Leandro)', '', ''),
  ('Mariela amiga Laura (Calasanz)', '', ''),
  ('Marina Montesino', '', ''),
  ('Marisol Pascual (Calcuta)', '', ''),
  ('Meli Giordano (vecina)', '', ''),
  ('Merce Guiroy (Calasanz)', '', ''),
  ('Mercedes Sancho', '', ''),
  ('Micaela Duin (vecina)', '', ''),
  ('Mónica Lledó', '', ''),
  ('Naty (amiga Mariana Aceto)', '', ''),
  ('Nerina Martínez', '', ''),
  ('Pablo Pabezka', '', ''),
  ('Padre Eduardo', '', ''),
  ('Pía Bendolini', '', ''),
  ('Pilar Loring', '', ''),
  ('Silvia Sol', '', ''),
  ('Susi Morales', '', ''),
  ('Violeta (fraternidad)', '', ''),
  ('Yani vecina', '', ''),
  ('Yisela Aguilera (Calasanz)', '', '');

insert into products (name, factory_id, cost, price, stock, status)
select product_data.name, factories.id, product_data.cost, product_data.price, product_data.stock, product_data.status
from (values
  ('Alpargata yute original', 'Regionales FDL', 10800, 15120, 0, 'Activo'),
  ('Botas media caña brasileña', 'Regionales FDL', 29000, 40600, 0, 'Activo'),
  ('Chaleco gamuza', 'Regionales FDL', 18000, 25200, 0, 'Activo'),
  ('Bombachas de campo', 'Regionales FDL', 14800, 20720, 0, 'Activo'),
  ('Alpargatas simil yute', 'Regionales FDL', 4820, 6748, 0, 'Activo'),
  ('Termo bala', 'Regionales FDL', 11200, 15680, 0, 'Activo'),
  ('Set juego regional', 'Regionales FDL', 5990, 8386, 0, 'Activo'),
  ('Bombacha de campo grafa', 'Regionales FDL', 14000, 19600, 0, 'Activo'),
  ('Cinturón trenzado combinado x 12', 'Regionales FDL', 5000, 7000, 0, 'Activo'),
  ('Boina hilo', 'Regionales FDL', 5000, 7000, 0, 'Activo'),
  ('Bermuda cargo', 'Regionales FDL', 13000, 18200, 0, 'Activo'),
  ('Chomba pampa', 'Regionales FDL', 12000, 16800, 0, 'Activo'),
  ('Tabla pizzer', 'Regionales FDL', 3900, 5460, 0, 'Activo'),
  ('Bombilla alpaca plana', 'Regionales FDL', 3000, 4200, 0, 'Activo'),
  ('Ruana pampa', 'Regionales FDL', 24000, 33600, 0, 'Activo'),
  ('Billetera c volante cuero', 'Regionales FDL', 3500, 4900, 0, 'Activo'),
  ('Bufandones pahmina', 'Regionales FDL', 13000, 18200, 0, 'Activo'),
  ('Alpargata goma eva', 'Regionales FDL', 3848, 5387.2, 0, 'Activo'),
  ('Chomba pampero', 'Regionales FDL', 20860, 29204, 0, 'Activo'),
  ('Zapatillas jaguar', 'Regionales FDL', 7469, 10456.6, 0, 'Activo'),
  ('Bicicleta Explorer', 'Enrique Bicicletas', 285000, 400000, 0, 'Activo'),
  ('Zapato hombre', 'Regionales FDL', 10900, 15260, 0, 'Activo'),
  ('Cinturón bordado', 'Regionales FDL', 15000, 21000, 0, 'Activo'),
  ('Alpargatas estampadas', 'Regionales FDL', 5350, 7490, 0, 'Activo'),
  ('Camisa cuello mao', 'Regionales FDL', 15000, null, 0, 'Activo'),
  ('Campera pampa', 'Regionales FDL', 16500, null, 0, 'Activo'),
  ('Slip', 'Regionales FDL', 14500, null, 0, 'Activo'),
  ('Poncho niño', 'Regionales FDL', 15000, null, 0, 'Activo'),
  ('Poncho', 'Regionales FDL', 20000, null, 0, 'Activo'),
  ('Alpargata niño', 'Regionales FDL', 5200, null, 0, 'Activo'),
  ('Bombacha niño', 'Regionales FDL', 13000, null, 0, 'Activo'),
  ('Pañuelo cuello', 'Regionales FDL', 3700, 5900, 0, 'Activo'),
  ('Camisa clásica', 'Regionales FDL', 12000, 21000, 0, 'Activo'),
  ('Pasapañuelos', 'Regionales FDL', 1800, 2900, 0, 'Activo'),
  ('Pantalón cargo', 'Regionales FDL', 16000, null, 0, 'Activo'),
  ('Bombacha bordada', 'Regionales FDL', 16500, null, 0, 'Activo'),
  ('Mate imperial alpaca', 'Regionales FDL', 19000, null, 0, 'Activo'),
  ('Chaleco niño', 'Regionales FDL', 11000, null, 0, 'Activo'),
  ('Sombrero paja', 'Regionales FDL', 15000, null, 0, 'Activo'),
  ('Medias', 'Regionales FDL', 3000, null, 0, 'Activo'),
  ('Ruana', 'Regionales FDL', 20000, null, 0, 'Activo'),
  ('Cinturón cuero', 'Regionales FDL', 12000, 24000, 0, 'Activo'),
  ('Campera niño', 'Regionales FDL', 14500, null, 0, 'Activo'),
  ('Billetera en caja', 'Regionales FDL', 6000, null, 0, 'Activo'),
  ('Boina niño', 'Regionales FDL', 13000, null, 0, 'Activo'),
  ('Canasta matera', 'Regionales FDL', 28000, null, 0, 'Activo'),
  ('Bufandón', 'Regionales FDL', 20000, null, 0, 'Activo'),
  ('Alpargatas combinadas goma eva', 'Regionales FDL', 4560, 9800, 0, 'Activo'),
  ('Alpargatas faja pampa', 'Regionales FDL', 6900, 13800, 0, 'Activo'),
  ('Alpargatas guarda pampa goma eva', 'Regionales FDL', 4700, 9800, 0, 'Activo'),
  ('Buzo micropolar', 'Regionales FDL', 15900, null, 0, 'Activo'),
  ('Cintos hebillones', 'Regionales FDL', 9500, 16900, 0, 'Activo'),
  ('Pulsera cuero', 'Regionales FDL', 3200, 6400, 0, 'Activo'),
  ('Bicicleta turquesa', 'Enrique Bicicletas', 160200, 210000, 0, 'Activo'),
  ('Chomba pampa niño', 'Regionales FDL', 10000, null, 0, 'Activo'),
  ('Boina hilo bordada', 'Regionales FDL', 7500, 12500, 0, 'Activo'),
  ('Corbatín bordado', 'Regionales FDL', 3000, null, 0, 'Activo')
) as product_data(name, factory_name, cost, price, stock, status)
left join factories on factories.name = product_data.factory_name;

